// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


//   'use client'; // Add this line at the top

//   import type { Metadata } from "next";
//   import { Inter } from "next/font/google";
//   import "./globals.css";
//   import useSmoothScroll from "@/hooks/useSmoothScroll"; // Import the hook

//   const inter = Inter({ subsets: ["latin"] });

//   // Note: We can't export Metadata from a client component, 
//   // so we remove it for now. We can handle titles differently later.

//   export default function RootLayout({
//     children,
//   }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   // Call the hook here to activate smooth scrolling
//   useSmoothScroll();

//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


// import { Inter } from "next/font/google";
// import "./globals.css";
// import useSmoothScroll from "@/hooks/useSmoothScroll";
// import type { Metadata } from 'next';

// const inter = Inter({ subsets: ["latin"] });

// // --- THIS IS THE PART TO UPDATE ---
// export const metadata: Metadata = {
//   title: {
//     default: 'MidnightDev | Full-Stack Developer', // The title for your homepage
//     template: '%s | MidnightDev', // A template for other pages (e.g., "About | MidnightDev")
//   },
//   description: 'The personal portfolio of Akash Chawla, a passionate Full-Stack MERN developer specializing in building modern web applications.',
//   keywords: ['Akash Chawla', 'MidnightDev', 'Full-Stack Developer', 'MERN Stack', 'React Developer', 'Next.js', 'Portfolio', 'Delhi'],
//   authors: [{ name: 'Akash Chawla' }],
//   openGraph: {
//     title: 'MidnightDev | Full-Stack Developer',
//     description: 'Explore the portfolio of Akash Chawla, a creative and skilled MERN stack developer.',
//     url: 'https://your-live-domain.com', // Replace with your live URL
//     siteName: 'MidnightDev Portfolio',
//     images: [
//       {
//         url: '/og-image.png',
//         width: 1200,
//         height: 630,
//       },
//     ],
//     locale: 'en_US',
//     type: 'website',
//   },
// };
// // ---------------------------------

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   useSmoothScroll();

//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// NO 'use client' at the top of this file

import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from 'next';
import SmoothScrollProvider from './components/SmoothScrollProvider';
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

// Your metadata object for SEO lives here
export const metadata: Metadata = {
  title: {
    default: 'MidnightDev | Full-Stack Developer',
    template: '%s | MidnightDev',
  },
  description: 'The personal portfolio of Akash Chawla, a passionate Full-Stack MERN developer specializing in building modern web applications.',
  // ... all your other metadata ...
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* We wrap the children with our new client component */}
        <SmoothScrollProvider>
          {children}
        </SmoothScrollProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}